# frozen_string_literal: true

source 'https://rubygems.org'

gemspec name: 'eyes_core', path: './eyes_core/'
gemspec :name => 'eyes_selenium', :development_group => :eyes_selenium, path: './eyes_selenium/'
gemspec :name => 'eyes_images', :development_group => :eyes_images, path: './eyes_images/'
gemspec :name => 'eyes_calabash', :development_group => :eyes_calabash, path: './eyes_calabash/'
gemspec :name => 'eyes_capybara', :development_group => :eyes_capybara, path: './eyes_capybara/'
gemspec :name => 'eyes_appium', :development_group => :eyes_appium, path: './eyes_appium/'

gemspec name: 'eyes_universal', path: './eyes_universal/'

gem 'parallel_tests', group: [:development, :test]
gem 'rspec_junit_formatter'
# gem 'httpx', path: '../../httpx'
