require 'rubygems'
require 'rake/clean'

CURRENT_VERSION_PATH = File.expand_path('../../lib/applitools/version', File.dirname(__FILE__))
require CURRENT_VERSION_PATH
DOWNLOADER_PATH = File.expand_path('../../lib/applitools/universal_sdk/universal_server_downloader', File.dirname(__FILE__))
require DOWNLOADER_PATH

desc "Download universal server binaries"
task :default => [:prepare_server]

# depricated
file "get_server" do
  Applitools::UniversalServerDownloader.download(File.dirname(__FILE__))
end

# depricated
file "get_server_compressed" do
  Applitools::UniversalServerDownloader.tar_gz_download(File.dirname(__FILE__))
end

# install
file "prepare_server" do
  Applitools::UniversalServerDownloader.prepare_server(File.dirname(__FILE__))
end

# build
file "get_compress_all_binaries" do
  Applitools::UniversalServerDownloader.get_compress_all_binaries(File.dirname(__FILE__))
end