# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in eyes_universal.gemspec
gemspec

gem "rake", "~> 13.0"

gem 'rspec'
gem 'parallel_tests'
gem 'rspec_junit_formatter'
